package com.jiaty.demo.mybatis.model;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sno
     *
     * @mbggenerated Tue Jun 02 18:48:21 CST 2020
     */
    private Integer sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sname
     *
     * @mbggenerated Tue Jun 02 18:48:21 CST 2020
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sage
     *
     * @mbggenerated Tue Jun 02 18:48:21 CST 2020
     */
    private Integer sage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ssex
     *
     * @mbggenerated Tue Jun 02 18:48:21 CST 2020
     */
    private String ssex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sno
     *
     * @return the value of student.sno
     *
     * @mbggenerated Tue Jun 02 18:48:21 CST 2020
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sno
     *
     * @param sno the value for student.sno
     *
     * @mbggenerated Tue Jun 02 18:48:21 CST 2020
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sname
     *
     * @return the value of student.sname
     *
     * @mbggenerated Tue Jun 02 18:48:21 CST 2020
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sname
     *
     * @param sname the value for student.sname
     *
     * @mbggenerated Tue Jun 02 18:48:21 CST 2020
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sage
     *
     * @return the value of student.sage
     *
     * @mbggenerated Tue Jun 02 18:48:21 CST 2020
     */
    public Integer getSage() {
        return sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sage
     *
     * @param sage the value for student.sage
     *
     * @mbggenerated Tue Jun 02 18:48:21 CST 2020
     */
    public void setSage(Integer sage) {
        this.sage = sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ssex
     *
     * @return the value of student.ssex
     *
     * @mbggenerated Tue Jun 02 18:48:21 CST 2020
     */
    public String getSsex() {
        return ssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ssex
     *
     * @param ssex the value for student.ssex
     *
     * @mbggenerated Tue Jun 02 18:48:21 CST 2020
     */
    public void setSsex(String ssex) {
        this.ssex = ssex == null ? null : ssex.trim();
    }
}